### ISSUE TITLE
kit-typescript config update

### ISSUE THREAD

**Issue by cecilphillip** [aurelia/beginner-kits#17]
When I downloaded the kit-typescript from the aurelia docs, I got a blank page when I try to run it. To get it to work for me, I made some small tweaks to the config.js

Before
``` javascript
System.config({
  baseURL: "src",

 packages: {
    "../src": {
      "main": "app",
      "defaultExtension": "ts",
       ...........  
  },
});
```
After
``` javascript
System.config({
  baseURL: "/",

packages: {
    "src": {
      "main": "app",
      "defaultExtension": "ts",
       .........
  },
});
```

Then in index.html, I removed the aurelia-app attribute from the body and did a manual boot
```javascript
  <body>
    <script src="jspm_packages/system.js"></script>
    <script src="config.js"></script>
    <script>
      System.import('aurelia-bootstrapper').then(function(boot){
          boot.bootstrap(function(aurelia) {
            aurelia.use
                .standardConfiguration()
                .developmentLogging();

            aurelia.start().then(() => aurelia.setRoot('src/app', document.body));
        });
      });
    </script>
  </body>
```

**Comment by JoshMcCullough** [comment]
This worked for me. I had the same symptoms. Not sure why the manual bootstrapping step is required, or what the "real" fix is, but it'd be good if the starter kits worked out of the box!

**Comment by EisenbergEffect** [comment]
That's odd. I personally tested these kits and confirmed they were working. Can you provide some more information about the context in which they were run?

**Comment by JoshMcCullough** [comment]
Hi Rob. Okay, so maybe I didn't follow the directions _exactly_. The sample runs fine out of the box, but once I run `jspm install`, the sample breaks. So JSPM is altering some config/etc., I presume, which is breaking the sample.

Also, when I clone this repo, move to `kit-typescript`, run `jspm install`, then start the HTTP server, it doesn't work. So something's out of sync, perhaps.

I'm using:
- Node v5.10
- JSPM v0.16.32

So I was able to get a real error, but it could be a red herring. I installed JSPM locally (`npm install jspm`) and then ran `jspm install` again, and started the HTTP server. Now I get this error:

```
Uncaught (in promise) Error: Error: Plugin http://127.0.0.1:8080/src/jspm_packages/github/frankwallis/plugin-typescript@2.6.0.js cannot load itself, make sure it is excluded from any wildcard meta configuration via a custom loader: false rule.
	Error loading http://127.0.0.1:8080/src/jspm_packages/github/frankwallis/plugin-typescript@2.6.0.js
	Error loading http://127.0.0.1:8080/src/jspm_packages/npm/aurelia-bootstrapper@1.0.0-beta.1.1.2.js
```

Hope this helps!

**Comment by EisenbergEffect** [comment]
Ok, yes, yes. You cannot run jspm install on the beginner kit. It's designed specifically for the beginner scenario only. We should probably add a note to the guide on that. Would you be interested in submitting a PR to improve our documentation? You can find the docs in the framework repo under the doc folder.

**Comment by JoshMcCullough** [comment]
I can do that. But I'd also suggest that the "beginner kit" is likely to be used (as is my case) as a starting point for an actual project. In that case, I think I should be able to expand the kit to include more packages, etc. 

If that's not what these kits are meant for, then fine, but that was my expectation.

**Comment by EisenbergEffect** [comment]
Ultimately, we'll probably get rid of these kits. We are working on a new CLI that should make getting started much easier. So, we're hesitant to spend too much time tweaking them now.

**Comment by JoshMcCullough** [comment]
Ah, cool -- sounds good.

**Comment by EisenbergEffect** [comment]
We are working on it now, for the initial launch we want to have a startup something like this:

1. Begin by installing NodeJS if you don't already have it. You can [download the latest version here](https://nodejs.org/en/).
2. From the command line execute `npm install -g aurelia-cli` to install Aurelia's tooling.
3. From the command line execute `aurelia new hello-world` to create your first Aurelia project. When prompted, select "express" if you want to use the default setup or "custom" if you want to make your own choice of transpiler, css preprocessor, etc.
4. From the command line execute `cd hello-world` to change into the directory of your new project.
5. From the command line execute `aurelia run` to build the app and run our development server. You can now browse to `localhost:9000` to see the application.

**Comment by JoshMcCullough** [comment]
Very nice, love it.

**Comment by atsu85** [comment]
@EisenbergEffect, that sound nice, however I'm wondering about the reasons to create (actually resurect [deprecated](https://github.com/aurelia/cli/commit/a1e7cd5bb1f9262f7b4a075692fe3b83eb9002de) project) aurelia-cli for generating the project instead of using Yeoman (that is well documented and might be already familiar to some of the potential contributors)?

I saw, that currently @zewa666's Aurelia [project generator](https://github.com/zewa666/generator-aurelia) that is implemented with Yeoman is just downloading selected skeleton variant from [github](https://github.com/aurelia/skeleton-navigation/) and adds simple commands to [update](https://github.com/zewa666/generator-aurelia/blob/master/update/index.js) aurelia version and to generate new [page](https://github.com/zewa666/generator-aurelia/blob/master/page/index.js), but I'm sure this isn't the limit of Yeoman. I've seen great [presentation](https://www.youtube.com/watch?v=baVOGuFIe9M) about [Angular 1 Yeoman generator](https://github.com/yeoman/generator-angular) and i was very impressed (it also supports alternative languages for TypeScript and CoffeScript).

**Comment by EisenbergEffect** [comment]
The CLI will do everything that a developer needs: create projects, build, bundle, test, install libraries, etc. It's very odd when someone comes to try out Aurelia and they have to install 3rd party libraries in order to use our library. That doesn't instill confidence and it makes us dependent, at our core, on the work of other people that we cannot control. Also, looking at some trends, I think Yeoman is on the way out. We can do a lot more with our own CLI and it helps us to solve a bunch of other problems besides project creation. Once it's ready, we'll have an Aurelia tooling story that has no dependencies outside of npm and the browser. No need for jpsm, gulp, etc.

**Comment by Gheoan** [comment]
Ember also went for a CLI instead of `yeoman`.
